/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as MinhaListaRouteImport } from './routes/minha-lista'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as DoramaSlugRouteImport } from './routes/dorama.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaListaRoute = MinhaListaRouteImport.update({
  id: '/minha-lista',
  path: '/minha-lista',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const DoramaSlugRoute = DoramaSlugRouteImport.update({
  id: '/dorama/$slug',
  path: '/dorama/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/minha-lista': typeof MinhaListaRoute
  '/planos': typeof PlanosRoute
  '/dorama/$slug': typeof DoramaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/minha-lista': typeof MinhaListaRoute
  '/planos': typeof PlanosRoute
  '/dorama/$slug': typeof DoramaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/minha-lista': typeof MinhaListaRoute
  '/planos': typeof PlanosRoute
  '/dorama/$slug': typeof DoramaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo' | '/minha-lista' | '/planos' | '/dorama/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo' | '/minha-lista' | '/planos' | '/dorama/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/minha-lista'
    | '/planos'
    | '/dorama/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  MinhaListaRoute: typeof MinhaListaRoute
  PlanosRoute: typeof PlanosRoute
  DoramaSlugRoute: typeof DoramaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-lista': {
      id: '/minha-lista'
      path: '/minha-lista'
      fullPath: '/minha-lista'
      preLoaderRoute: typeof MinhaListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dorama/$slug': {
      id: '/dorama/$slug'
      path: '/dorama/$slug'
      fullPath: '/dorama/$slug'
      preLoaderRoute: typeof DoramaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  MinhaListaRoute: MinhaListaRoute,
  PlanosRoute: PlanosRoute,
  DoramaSlugRoute: DoramaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
